service: url-shortner

provider:
 name: aws
 runtime: nodejs6.10
 memorySize: 128
 timeout: 10
 stage: prod
 region: us-east-1 #region to host aws lambda
 profile: AWS_PROFILE #these takes aws cli profile from your machine

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /
